### ISSUE TITLE
Use Kotlin 1.5's value class 

### ISSUE THREAD

**Issue by CXwudi** [michaelbull/kotlin-inline-logger#2]
Inline class in Kotlin 1.4 has been deprecated and it is recommended to use value class introduced in Kotlin 1.5. 

Value class is basically the same as inline class, but it's the stable feature now

**Comment by CXwudi** [comment]
Oh well, I end up creating my own Kotlin inline logging library using Kotlin 1.5 value class, https://github.com/CXwudi/kotlin-jvm-1_5-inline-logging

The library is very small, only two source files and it gets the job done very well

**Comment by rgmz** [comment]
The naive approach (for this library) would be to replace `inline class` with `@JvmInline value class`, as there's currently only a Jvm implementation:
https://github.com/michaelbull/kotlin-inline-logger/blob/3b5e28108132a816365d93f9d2f329c2e90daa50/src/commonMain/kotlin/com/github/michaelbull/logging/InlineLogger.kt#L10

Properly implementing value classes would be a bit painful. You'd seemingly need to change `inline class InlineLogger` to `expect value class InlineLogger` and then re-implement each function in `jvmMain` because "Expected declaration must not have a body":
![image](https://user-images.githubusercontent.com/32133502/139760307-e0f0341a-3bc7-4230-bdde-abf37de6390d.png)

**Comment by CXwudi** [comment]
I haven't tried to combine `expect/actual class` with `value class`. With the `value class`, you can't have `val` but just  `inline val` since the value class can only contain one property. (actual you can have `val`, but with a `get()` as the backend)

**Comment by rgmz** [comment]
> I haven't tried to combine `expect/actual class` with `value class`. With the `value class`, you can't have `val` but just `inline val` since the value class can only contain one property.

It's a bit of a strange interaction. You can't `expect` a  `val` with a getter because it isn't allowed to have a body, and without a body the compiler thinks you're defining a property with a backing field ("Inline class cannot have properties with backing fields"). However, you can still define [computed properties](https://kotlinlang.org/docs/inline-classes.html#members) on the `actual` implementation.

I created #4 as an example of what that could look like.
https://github.com/michaelbull/kotlin-inline-logger/blob/80d19d547e97a2135619937ef865b07f6c8432d5/src/jvmMain/kotlin/com/github/michaelbull/logging/InlineLogger.kt#L30-L31

**Comment by CXwudi** [comment]
I just realized @michaelbull doesn't make the `InlineLogger` class an `expect` or `actual` class to achieve multi-platform support. He simply leaves  `InlineLogger` as a normal inline class in `commonMain` and lets `Logger` & `Marker` be `expect class/interface`. Have you tried not making `InlineLogger` as an `expect/actual class` but simply just change the `inline` keyword to `value`

**Comment by rgmz** [comment]
> Have you tried not making `InlineLogger` as an `expect/actual class` but simply just change the `inline` keyword to `value`

It doesn't compile without the `@JvmInline` annotation :confused::
```
e: ~/dev/michaelbull/kotlin-inline-logger/src/commonMain/kotlin/com/github/michaelbull/logging/InlineLogger.kt: (10, 1): Value classes without @JvmInline annotation are not supported yet
```

That said, it may be perfectly legal to use `@JvmInline` in `commonMain`. My assumption was that it could only be used in `jvmMain`, but I'm not familiar enough with multi-platform to say for certain. My initial suggestion complies without errors or warnings:
> The naive approach (for this library) would be to replace inline class with @JvmInline value class, as there's currently only a Jvm implementation:

**Comment by CXwudi** [comment]
Ohh, now I understood why would you change `inline class InlineLogger` to `expect value class InlineLogger` and the problem with expect class. 

A solution can be changing `inline class InlineLogger` to `interface InlineLogger` (or maybe `expect interface InlineLogger`, currently I am not sure what's the difference between normal interface and `expect interface`) and let `expect value class InlineLogger` in `jvmMain` to implement the interface, but that would break the purpose of having the advantage of inline class when referring the logger with the interface type.

So I guess putting a `@JvmInline` in `commonMain` may be the only solution? Or another breaking solution could be just changing all `val` to `fun` 😥

**Comment by CXwudi** [comment]
Actually, is it legal to `expect` a `val` (or `inline val`) with an empty `get()`
